---
- name: Docker installation using Ansible
  hosts: docker
  gather_facts: False
  become: true
  tasks:
  - name: Install packages
    ansible.builtin.yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes

  - name: Install required system packages
    ansible.builtin.yum:
      name: docker
      state: present
      update_cache: yes

  - name: Install docker module for python
    ansible.builtin.pip:
      name: "{{ item.name }}"
      state: present
      executable: pip3
    with_items:
    - { name: docker}
    - { name: six}

  - name: Starting docker service
    ansible.builtin.service:
      name: "docker"
      state: started
      enabled: yes
      
  - name: Remove image
    community.docker.docker_image:
      state: absent
      name: artifactory.dagility.com/docker-services-training/aleesha/react_app
      tag: latest
      force_absent: yes

  - name: Deleting containers
    community.general.docker_container:
     name: react_app
     state: absent
  
  - name: Logging in to registry
    community.docker.docker_login:
      registry: https://artifactory.dagility.com
      username: 'services-training'
      password: "{{ password }}"
      state: present
 
  - name: Docker image pull
    community.docker.docker_image:
      source: pull
      name: artifactory.dagility.com/docker-services-training/aleesha/react_app:latest

  - name: Creating container to run React_app
    community.general.docker_container:
     name: react_app
     image: artifactory.dagility.com/docker-services-training/aleesha/react_app:latest
     ports:
       - "3000:5000"
     state: started

  
  

